-- 1. Create PROFILES Table
-- This table stores additional info about users
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
  full_name TEXT,
  avatar_url TEXT,
  updated_at TIMESTAMP WITH TIME ZONE
);

-- Enable RLS for profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile." ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Trigger to create profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url)
  VALUES (NEW.id, NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'avatar_url');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 2. Create TASKS Table
CREATE TABLE public.tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  due_date TIMESTAMP WITH TIME ZONE,
  due_at TIMESTAMP WITH TIME ZONE, -- for Web compatibility
  is_completed BOOLEAN DEFAULT FALSE,
  completed BOOLEAN DEFAULT FALSE, -- for Web compatibility
  completed_at TIMESTAMP WITH TIME ZONE, -- for Web compatibility
  reminder_at TIMESTAMP WITH TIME ZONE, -- for Web compatibility
  category TEXT DEFAULT 'general', -- for Web compatibility
  priority TEXT DEFAULT 'Medium',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Trigger to sync Android and Web task columns
CREATE OR REPLACE FUNCTION sync_task_columns()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    IF NEW.is_completed IS NOT NULL AND NEW.completed IS NULL THEN
      NEW.completed := NEW.is_completed;
    ELSIF NEW.completed IS NOT NULL AND NEW.is_completed IS NULL THEN
      NEW.is_completed := NEW.completed;
    END IF;

    IF NEW.due_date IS NOT NULL AND NEW.due_at IS NULL THEN
      NEW.due_at := NEW.due_date;
    ELSIF NEW.due_at IS NOT NULL AND NEW.due_date IS NULL THEN
      NEW.due_date := NEW.due_at;
    END IF;
  ELSE
    IF NEW.is_completed IS DISTINCT FROM OLD.is_completed THEN
      NEW.completed := NEW.is_completed;
    ELSIF NEW.completed IS DISTINCT FROM OLD.completed THEN
      NEW.is_completed := NEW.completed;
    END IF;

    IF NEW.due_date IS DISTINCT FROM OLD.due_date THEN
      NEW.due_at := NEW.due_date;
    ELSIF NEW.due_at IS DISTINCT FROM OLD.due_at THEN
      NEW.due_date := NEW.due_at;
    END IF;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trg_sync_task_columns
  BEFORE INSERT OR UPDATE ON public.tasks
  FOR EACH ROW EXECUTE FUNCTION sync_task_columns();

-- Enable RLS for tasks
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Individuals can view their own tasks." ON public.tasks FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Individuals can create their own tasks." ON public.tasks FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Individuals can update their own tasks." ON public.tasks FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Individuals can delete their own tasks." ON public.tasks FOR DELETE USING (auth.uid() = user_id);

-- 3. Create BILLS Table
CREATE TABLE public.bills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users NOT NULL,
  title TEXT NOT NULL,
  amount DECIMAL NOT NULL,
  due_date DATE,
  status TEXT DEFAULT 'Pending', -- 'Pending', 'Paid', 'Overdue'
  category TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for bills
ALTER TABLE public.bills ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Individuals can view their own bills." ON public.bills FOR SELECT USING (auth.uid() = user_id);

-- 4. Create NOTIFICATIONS Table
CREATE TABLE public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users NOT NULL,
  title TEXT NOT NULL,
  message TEXT,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for notifications
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Individuals can view their own notifications." ON public.notifications FOR SELECT USING (auth.uid() = user_id);

-- 5. Create ENVIRONMENT Table (Global)
CREATE TABLE public.environment_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location_name TEXT,
  aqi INTEGER,
  temperature DECIMAL,
  humidity DECIMAL,
  recorded_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.environment_data ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Everyone can view environment data." ON public.environment_data FOR SELECT USING (true);

-- 6. Create HOSPITALS Table
CREATE TABLE public.hospitals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  address TEXT,
  phone TEXT,
  latitude DECIMAL,
  longitude DECIMAL,
  rating DECIMAL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.hospitals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Everyone can view hospitals." ON public.hospitals FOR SELECT USING (true);

-- 7. Create TRANSPORT Table
CREATE TABLE public.transport_routes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  route_name TEXT NOT NULL,
  vehicle_type TEXT, -- 'Bus', 'Metro', 'Train'
  departure_time TIME,
  arrival_time TIME,
  source TEXT,
  destination TEXT,
  fare DECIMAL
);

ALTER TABLE public.transport_routes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Everyone can view transport routes." ON public.transport_routes FOR SELECT USING (true);

-- 8. Create EMERGENCY_CONTACTS Table
CREATE TABLE public.emergency_contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_name TEXT NOT NULL,
  phone_number TEXT NOT NULL,
  category TEXT -- 'Police', 'Ambulance', 'Fire'
);

ALTER TABLE public.emergency_contacts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Everyone can view emergency contacts." ON public.emergency_contacts FOR SELECT USING (true);

-- 9. Insert Sample Data
INSERT INTO public.environment_data (location_name, aqi, temperature, humidity)
VALUES ('Ambattur, Chennai', 42, 34.0, 72.0);

INSERT INTO public.hospitals (name, address, phone, latitude, longitude, rating)
VALUES
('Apollo Hospital', 'Greams Road, Chennai', '+91 44 2829 3333', 13.0645, 80.2514, 4.5),
('Fortis Malar', 'Adyar, Chennai', '+91 44 4242 4242', 13.0067, 80.2575, 4.2);

INSERT INTO public.emergency_contacts (service_name, phone_number, category)
VALUES
('Police', '100', 'Police'),
('Ambulance', '108', 'Ambulance'),
('Fire Brigade', '101', 'Fire');

INSERT INTO public.transport_routes (route_name, vehicle_type, source, destination, fare)
VALUES
('Route 23A', 'Bus', 'Ambattur', 'Broadway', 15.0),
('Blue Line', 'Metro', 'Wimco Nagar', 'Airport', 60.0);
